[package]
authors = ["Roma Sokolov", "Alexander Zhuravlev <123368+bofh@users.noreply.github.com>"]
edition = "2018"
name = "fcfs-rtfm"
readme = "README.md"
version = "0.1.0"
[[bin]]
bench = false
name = "fcfs-rtfm"
test = false

[dependencies]
cortex-m = "0.5.8"
cortex-m-rt = "0.6.7"
cortex-m-rtfm = "0.4.1"
cortex-m-semihosting = "0.3.2"
panic-halt = "0.2.0"
panic-semihosting = "0.5.1"
stm32f30x = "0.8.0"

[dependencies.mpu9250]
version = "0.7.4"

[dependencies.hal]
# version = "0.11.0"
git = "https://github.com/copterust/alt-stm32f30x-hal"
package = "alt-stm32f30x-hal"
features = ["rt"]

[profile]
[profile.release]
codegen-units = 1
debug = true
lto = true
incremental = false
