[package]
authors = ["Alexander Zhuravlev <123368+bofh@users.noreply.github.com>"]
edition = "2018"
name = "fcfs-rtfm"
readme = "README.md"
version = "0.1.0"
[[bin]]
bench = false
name = "fcfs-rtfm"
test = false

[dependencies]
cortex-m = "0.5.8"
cortex-m-rt = "0.6.5"
cortex-m-rtfm = "*"
cortex-m-semihosting = "0.3.2"
stm32f30x = {version = "0.8.0", features = ["rt"]}
panic-halt = "0.2.0"
panic-semihosting = "*"

[dependencies.hal]
# version = "0.11.0"
git = "https://github.com/copterust/alt-stm32f30x-hal"
package = "alt-stm32f30x-hal"
features = ["rt"]

[profile]
[profile.release]
codegen-units = 1
debug = true
lto = true
